name: pbmp
params:
  input_dim: 24
  hidden_dim: 128
  num_hidden_layers: 4
  # Simulator params
  temperature: 0.05
  timestep: 0.05
  n_steps: 100
  k: 20
  input_dim: 24
  hidden_dim: 128
  num_hidden_layers: 4