name: test
device: gpu
training:
  loss: msd
  epochs: 10
  batch_size: 1
  lr: 0.005
  logging_freq: 20
  val_check_interval: 0.2
simulator:
  temperature: 0.05
  n_steps: 20
  time_step: 0.05
  k: 20
defaults:
  - dataset: greener
  - model: pbmp