name: test
device: cuda
training:
  loss: rmsd
  epochs: 10
  batch_size: 1
  lr: 0.0005
  logging_freq: 10
simulator:
  temperature: 0.05
  n_steps: 150
  time_step: 0.05
  k: 20
defaults:
  - dataset: greener
  - model: gns